import { Merchant } from "@/lib/types/merchant";

export const mockMerchants: Merchant[] = [
  {
    id: "mch_001",
    companyName: "TechGadgets Inc",
    legalEntity: "TechGadgets Inc.",
    contactEmail: "finance@techgadgets.com",
    contactPhone: "+1 555-0100",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-03-20T14:30:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "daily",
    bankAccount: {
      accountName: "TechGadgets Inc",
      accountNumber: "****4567",
      bankName: "Chase Bank",
      routingNumber: "****1234",
    },
    supportedChains: ["ethereum", "polygon", "base"],
    supportedTokens: ["USDC", "USDT"],
    totalVolume: 1250000.5,
    transactionCount: 3420,
  },
  {
    id: "mch_002",
    companyName: "Fashion Forward",
    legalEntity: "Fashion Forward LLC",
    contactEmail: "payments@fashionforward.com",
    contactPhone: "+1 555-0101",
    status: "active",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-03-19T11:20:00Z",
    settlementCurrency: "EUR",
    settlementFrequency: "weekly",
    bankAccount: {
      accountName: "Fashion Forward LLC",
      accountNumber: "****7890",
      bankName: "Deutsche Bank",
      routingNumber: "****5678",
    },
    supportedChains: ["ethereum", "polygon"],
    supportedTokens: ["USDC"],
    totalVolume: 890000.25,
    transactionCount: 2150,
  },
  {
    id: "mch_003",
    companyName: "GameZone Studios",
    legalEntity: "GameZone Studios Ltd",
    contactEmail: "billing@gamezone.io",
    contactPhone: "+44 20 7946 0958",
    status: "pending_kyc",
    createdAt: "2024-03-18T14:00:00Z",
    updatedAt: "2024-03-18T14:00:00Z",
    settlementCurrency: "GBP",
    settlementFrequency: "weekly",
    bankAccount: {
      accountName: "GameZone Studios Ltd",
      accountNumber: "****1234",
      bankName: "Barclays",
      routingNumber: "****9012",
    },
    supportedChains: ["ethereum", "base"],
    supportedTokens: ["USDC", "USDT", "ETH"],
    totalVolume: 0,
    transactionCount: 0,
  },
  {
    id: "mch_004",
    companyName: "Green Energy Co",
    legalEntity: "Green Energy Corporation",
    contactEmail: "accounting@greenenergy.com",
    contactPhone: "+1 555-0102",
    status: "suspended",
    createdAt: "2023-11-10T08:00:00Z",
    updatedAt: "2024-03-15T16:45:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "monthly",
    bankAccount: {
      accountName: "Green Energy Corporation",
      accountNumber: "****3456",
      bankName: "Bank of America",
      routingNumber: "****7890",
    },
    supportedChains: ["ethereum"],
    supportedTokens: ["USDC"],
    totalVolume: 450000.0,
    transactionCount: 890,
  },
  {
    id: "mch_005",
    companyName: "Artisan Coffee",
    legalEntity: "Artisan Coffee Roasters Inc",
    contactEmail: "finance@artisancoffee.com",
    contactPhone: "+1 555-0103",
    status: "active",
    createdAt: "2024-01-20T11:30:00Z",
    updatedAt: "2024-03-20T09:15:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "daily",
    bankAccount: {
      accountName: "Artisan Coffee Roasters Inc",
      accountNumber: "****5678",
      bankName: "Wells Fargo",
      routingNumber: "****2345",
    },
    supportedChains: ["polygon", "base"],
    supportedTokens: ["USDC"],
    totalVolume: 325000.75,
    transactionCount: 4200,
  },
  {
    id: "mch_006",
    companyName: "Digital Books Plus",
    legalEntity: "Digital Books Plus LLC",
    contactEmail: "payments@digitalbooksplus.com",
    contactPhone: "+1 555-0104",
    status: "active",
    createdAt: "2024-02-15T13:00:00Z",
    updatedAt: "2024-03-19T17:30:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "weekly",
    bankAccount: {
      accountName: "Digital Books Plus LLC",
      accountNumber: "****9012",
      bankName: "US Bank",
      routingNumber: "****6789",
    },
    supportedChains: ["ethereum", "polygon", "base"],
    supportedTokens: ["USDC", "USDT"],
    totalVolume: 178500.0,
    transactionCount: 1560,
  },
  {
    id: "mch_007",
    companyName: "Fitness First",
    legalEntity: "Fitness First International",
    contactEmail: "billing@fitnessfirst.com",
    contactPhone: "+1 555-0105",
    status: "offboarded",
    createdAt: "2023-08-01T10:00:00Z",
    updatedAt: "2024-02-28T12:00:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "monthly",
    bankAccount: {
      accountName: "Fitness First International",
      accountNumber: "****3456",
      bankName: "Citibank",
      routingNumber: "****0123",
    },
    supportedChains: ["ethereum"],
    supportedTokens: ["USDC"],
    totalVolume: 95000.0,
    transactionCount: 340,
  },
  {
    id: "mch_008",
    companyName: "Smart Home Solutions",
    legalEntity: "Smart Home Solutions GmbH",
    contactEmail: "finance@smarthome.de",
    contactPhone: "+49 30 12345678",
    status: "pending_kyc",
    createdAt: "2024-03-19T09:00:00Z",
    updatedAt: "2024-03-19T09:00:00Z",
    settlementCurrency: "EUR",
    settlementFrequency: "weekly",
    bankAccount: {
      accountName: "Smart Home Solutions GmbH",
      accountNumber: "****7890",
      bankName: "Commerzbank",
      routingNumber: "****4567",
    },
    supportedChains: ["ethereum", "polygon"],
    supportedTokens: ["USDC", "USDT"],
    totalVolume: 0,
    transactionCount: 0,
  },
  {
    id: "mch_009",
    companyName: "Travel Adventures",
    legalEntity: "Travel Adventures Co",
    contactEmail: "accounting@traveladventures.com",
    contactPhone: "+1 555-0106",
    status: "active",
    createdAt: "2024-01-05T15:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "daily",
    bankAccount: {
      accountName: "Travel Adventures Co",
      accountNumber: "****1234",
      bankName: "PNC Bank",
      routingNumber: "****8901",
    },
    supportedChains: ["ethereum", "polygon", "base"],
    supportedTokens: ["USDC", "USDT", "ETH"],
    totalVolume: 2150000.0,
    transactionCount: 5670,
  },
  {
    id: "mch_010",
    companyName: "Pet Paradise",
    legalEntity: "Pet Paradise Inc",
    contactEmail: "payments@petparadise.com",
    contactPhone: "+1 555-0107",
    status: "active",
    createdAt: "2024-02-20T12:00:00Z",
    updatedAt: "2024-03-18T14:20:00Z",
    settlementCurrency: "USD",
    settlementFrequency: "weekly",
    bankAccount: {
      accountName: "Pet Paradise Inc",
      accountNumber: "****5678",
      bankName: "TD Bank",
      routingNumber: "****2345",
    },
    supportedChains: ["polygon", "base"],
    supportedTokens: ["USDC"],
    totalVolume: 567000.5,
    transactionCount: 3890,
  },
];

export function getMerchantById(id: string): Merchant | undefined {
  return mockMerchants.find((m) => m.id === id);
}

export function getMerchantsByStatus(status: string | null): Merchant[] {
  if (!status || status === "all") return mockMerchants;
  return mockMerchants.filter((m) => m.status === status);
}
